PutneyAndWood/Controllers/Opportunities/PipelineController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SnapSuite.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SnapSuite.Controllers
{
    [Authorize]
    public class PipelineController : ServiceEntityController<Opportunity, OpportunityViewModel, OpportunityService<OpportunityViewModel>>
    {
      
        public PipelineController()
            : base(new OpportunityService<OpportunityViewModel>(Guid.Empty, null, new OpportunityMapper(), new SnapDbContext()))
        {

        }


        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            if (ViewBag.ViewCRM == false)
               Response.Redirect("/");
        }


        #region Main Opportunity Page

        // GET: Opportunities
        public ActionResult Index(string id)
        {
            SetViewBags();
            if (!string.IsNullOrWhiteSpace(id))
                ViewBag.ID = id;
            return View();
        }

        public ActionResult Edit(Guid id)
        {
            return RedirectToAction("Index", new { id = id });
        }

        public void SaveCookies(string oppTypeID)
        {
            HttpCookie cookie = Request.Cookies["OpportunitySearch"] ?? new HttpCookie("OpportunitySearch");
            cookie["OppTypeID"] = oppTypeID;

            cookie.Expires = DateTime.Now.AddDays(1d);
            Response.Cookies.Add(cookie);
        }

        public ActionResult _Opportunities(string oppTypeID)
        {
            if (!string.IsNullOrWhiteSpace(oppTypeID))
            {
                SaveCookies(oppTypeID);
                var oppStatusService = new OpportunityStatusService<OpportunityStatusViewModel>(_service.CompanyID, _service.CurrentUserID, new OpportunityStatusMapper(), _service.DbContext);
                var models = oppStatusService.Read().Where(x => x.OpportunityTypeID.ToString() == oppTypeID).OrderBy(x => x.SortPos);

                var viewModel = models.ToList().Select(x => oppStatusService.MapToViewModel(x)).ToList();
                return PartialView(viewModel);
            }
            else
            {
                return PartialView(new List<OpportunityStatusViewModel>());
            }
        }

        [HttpGet]
        public ActionResult _NewOpportunity(string typeID, string statusID)
        {
            var oppType = new OpportunityTypeService<OpportunityTypeViewModel>(_service.CompanyID, _service.CurrentUserID, new OpportunityTypeMapper(), _service.DbContext).Find(Guid.Parse(typeID));
            var viewModel = new OpportunityViewModel() { LabelValue1 = oppType.LabelValue1, LabelValue2 = oppType.LabelValue2, AssignedUserID = CurrentUser.Id };

            if (!string.IsNullOrWhiteSpace(typeID) && typeID != "undefined")
            {
                viewModel.OpportunityTypeID = typeID;
            }
            if (!string.IsNullOrWhiteSpace(statusID) && statusID != "undefined")
            {
                viewModel.StatusID = statusID;
            }
            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _NewOpportunity(OpportunityViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }
            var model = _service.MapToModel(viewModel);
            model = _service.Create(model);
            
            // Add Log
            //AddLog(model.ID);

            return Json(new { ID = model.ID });
        }

        [HttpGet]
        public ActionResult _EditOpportunity(Guid ID)
        {
            var model = _service.FindByID(ID);
            var viewModel = _service.MapToViewModel(model);
            ViewBag.CurrentUserID = CurrentUser.Id;
            ViewBag.CurrentUserEmail = CurrentUser.Email;
            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _EditOpportunityDetails(OpportunityViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            _service.Update(viewModel);

            var model = _service.FindByID(Guid.Parse(viewModel.ID));
            viewModel = _service.MapToViewModel(model);
            ViewBag.Saved = true;
            return PartialView(viewModel);
        }

        [HttpGet]
        public ActionResult _NewEvent(Guid oppID, string eventAssignedUserID, string clientID, string contactID, string timestamp)
        {
            var opportunity = _service.FindByID(oppID);
            var viewModel = new OpportunityEventViewModel()
            {
                EventAssignedUserID = eventAssignedUserID?? opportunity.AssignedUserID,
                EventCreatorID = CurrentUser.Id,
                ClientID = clientID?? opportunity.ClientID.ToString(),
                ContactID = contactID?? opportunity.ClientContactID.ToString(),
                OpportunityID = opportunity.ID.ToString(),
                Timestamp = !string.IsNullOrEmpty(timestamp) ? DateTime.Parse(timestamp) : DateTime.Now
            };

            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _NewEvent(OpportunityEventViewModel viewModel, string MarkComplete, string MarkCompleteD1, string MarkCompleteD7, string MarkNotComplete)
        {
            if (ModelState.IsValid)
            {
                var service = new ClientEventService<OpportunityEventViewModel>(_service.CompanyID, null, _service.CurrentUserID, new OpportunityEventMapper(), _service.DbContext);
                //var mapper = new OpportunityEventMapper();

                if (MarkComplete != null || MarkCompleteD1 != null || MarkCompleteD7 != null)
                    viewModel.Complete = true;
                else if (MarkNotComplete != null)
                    viewModel.Complete = false;

                //var model = mapper.MapToModel(viewModel);
                //model.CompanyID = CurrentUser.CompanyID;
                //model.CreatorID = CurrentUser.Id;
                service.Create(viewModel);

                if (MarkCompleteD1 != null)
                {
                    return Json(new { Status = "Success", CreateNew = new { EventAssignedUserID = viewModel.EventAssignedUserID, ClientID = viewModel.ClientID, ContactID = viewModel.ContactID, Timestamp = viewModel.Timestamp.AddDays(1).ToString() } });
                }
                else if (MarkCompleteD7 != null)
                {
                    return Json(new { Status = "Success", CreateNew = new { EventAssignedUserID = viewModel.EventAssignedUserID, ClientID = viewModel.ClientID, ContactID = viewModel.ContactID, Timestamp = viewModel.Timestamp.AddDays(7).ToString() } });
                }
                else
                {
                    return Json(new { Status = "Success" });
                }
            }
            else
            {
                return PartialView(viewModel);
            }
        }

        [HttpGet]
        public ActionResult _EditEvent(Guid eventID)
        {
            var eventService = new ClientEventService<OpportunityEventViewModel>(_service.CompanyID, null, _service.CurrentUserID, new OpportunityEventMapper(), _service.DbContext);
            var viewModel = eventService.MapToViewModel(eventService.Find(eventID));

            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _EditEvent(OpportunityEventViewModel viewModel, string MarkComplete, string MarkCompleteD1, string MarkCompleteD7, string MarkNotComplete)
        {
            if (ModelState.IsValid)
            {
                var service = new ClientEventService<OpportunityEventViewModel>(_service.CompanyID, null, _service.CurrentUserID, new OpportunityEventMapper(), _service.DbContext);
                //var mapper = new OpportunityEventMapper();

                if (MarkComplete != null || MarkCompleteD1 != null || MarkCompleteD7 != null)
                    viewModel.Complete = true;
                else if (MarkNotComplete != null)
                    viewModel.Complete = false;

                //var model = service.FindByID(Guid.Parse(viewModel.ID));
                //mapper.MapToModel(viewModel, model);
                service.Update(viewModel);

                if (MarkCompleteD1 != null)
                {
                    return Json(new { Status = "Success", CreateNew = new { EventAssignedUserID = viewModel.EventAssignedUserID, ClientID = viewModel.ClientID, ContactID = viewModel.ContactID, Timestamp = viewModel.Timestamp.AddDays(1).ToString() } });
                }
                else if (MarkCompleteD7 != null)
                {
                    return Json(new { Status = "Success", CreateNew = new { EventAssignedUserID = viewModel.EventAssignedUserID, ClientID = viewModel.ClientID, ContactID = viewModel.ContactID, Timestamp = viewModel.Timestamp.AddDays(7).ToString() } });
                }
                else
                {
                    return Json(new { Status = "Success" });
                }
            }
            else
            {
                return PartialView(viewModel);
            }
        }

        #endregion

        public ActionResult ChangeStatus(Guid id, Guid statusID, int pos)
        {
            var model = _service.ChangeStatus(id, statusID, pos);
            
            return Json(new { Status = "Success" });
        }

        [HttpPost]
        public ActionResult Reorder(Guid id, int offset)
        {
            _service.Reorder(id, offset);

            return Json(new { Status = "Success" });
        }

        //public bool AddLog(Guid OpportunityID)
        //{

PutneyAndWood/Views/Pipeline/_EditEvent.cshtml
@model SnapSuite.Models.QuotationEventViewModel

<script>
    function OnEventContactChange(e) {
        var selected = this.dataItem();
        var title = selected.Title;
        var firstname = selected.FirstName;
        var lastname = selected.LastName;
        var email = selected.Email;
        var mobile = selected.Mobile;
        var telephone = selected.Telephone;
        var position = selected.Position;

        $('#divEditEvent label[name=label-contact-title]').text(title||"");
        $('#divEditEvent label[name=label-contact-firstname]').text(firstname||"");
        $('#divEditEvent label[name=label-contact-lastname]').text(lastname||"");
        $('#divEditEvent label[name=label-contact-email]').text(email||"");
        $('#divEditEvent label[name=label-contact-mobile]').text(mobile||"");
        $('#divEditEvent label[name=label-contact-telephone]').text(telephone||"");
        $('#divEditEvent label[name=label-contact-position]').text(position||"");
    }
</script>
<div id="divEditEvent">

    <div class="row">
        <div class="col-md-6">



            @using (Ajax.BeginForm("_EditEvent", "Pipeline", null, new AjaxOptions { UpdateTargetId = "divEditEvent", OnSuccess = "OnSaveEventSuccess" }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                //@Html.ValidationSummary(false, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.ClientID)

                <div class="row form-table">
                    <div class="col-sm-12">
                        @Html.HiddenFor(m => m.ID)
                        @Html.HiddenFor(m => m.CompanyID)
                        @Html.HiddenFor(m => m)
                        @Html.HiddenFor(m => m.Complete)
                        <table style="width:100%">
                            <tr>
                                <td style="width:100px;"><label>Timestamp:</label></td>
                                <td>
                                    @(Html.Kendo().DateTimePickerFor(m => m.Timestamp)
                                          .HtmlAttributes(new { style = "width:100%;" })
                                    )
                                    @Html.ValidationMessageFor(model => model.Timestamp, "", new { @style = "color: red;" })
                                </td>
                            </tr>
                            <tr>
                                <td><label>Contact:</label></td>
                                <td>
                                    @(Html.Kendo().DropDownListFor(model => model.ContactID)
                                          .DataTextField("Name")
                                          .DataValueField("ID")
                                          .OptionLabel("   ")
                                          .DataSource(source =>
                                          {
                                              source.Read(read => { read.Action("DropDownClientContacts", "ClientContacts").Data("function() { return { cltID: $('#ClientID').val() }}"); });
                                          })
                                          .Value(Model.ContactID)
                                          .Events(e => e.Change("OnEventContactChange").DataBound("OnEventContactChange"))
                                          .AutoBind(true)
                                          .HtmlAttributes(new { style = "width: 100%;" })
                                    )
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <div class="panel panel-info">
                                        <div class="panel-heading div-inline">
                                            Contact Details
                                        </div>
                                        <div class="panel-body" style="padding: 5px 15px 5px 15px;">
                                            <table style="margin-bottom: 0;">
                                                <tr>
                                                    <td style="width: 100px;"><label>Title:</label></td>
                                                    <td><label name="label-contact-title"></label></td>
                                                </tr>
                                                <tr>
                                                    <td><label>First Name:</label></td>
                                                    <td><label name="label-contact-firstname"></label></td>
                                                </tr>
                                                <tr>
                                                    <td><label>Last Name:</label></td>
                                                    <td><label name="label-contact-lastname"></label></td>
                                                </tr>
                                                <tr>
                                                    <td><label>Email:</label></td>
                                                    <td><label name="label-contact-email"></label></td>
                                                </tr>
                                                <tr>
                                                    <td><label>Mobile:</label></td>
                                                    <td><label name="label-contact-mobile"></label></td>
                                                </tr>
                                                <tr>
                                                    <td><label>Telephone:</label></td>
                                                    <td><label name="label-contact-telephone"></label></td>
                                                </tr>
                                                <tr>
                                                    <td><label>Position:</label></td>
                                                    <td><label name="label-contact-position"></label></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <table style="width:100%">
                            <tr>
                                <td>
                                    <label>Note:</label>
                                    @Html.TextAreaFor(model => model.Message, 2, 100, new { @class = "form-control", @style = "max-width:none; width:100%; resize:vertical;" })
                                    @Html.ValidationMessageFor(model => model.Message, "", new { @style = "color: red;" })
                                </td>
                            </tr>
                        </table>
                        <table style="width:100%">
                            <tr>
                                <td style="width:100px;"><label>Assigned User:</label></td>
                                <td>
                                    @(Html.Kendo().DropDownListFor(model => model.EventAssignedUserID)
                                          .DataTextField("Email").DataValueField("ID")
                                          .DataSource(source =>
                                          {
                                              source.Read(read => { read.Action("DropDownUsers", "Dropdowns"); });
                                          })
                                          .Value(Model.EventAssignedUserID)
                                          .AutoBind(true)
                                          .HtmlAttributes(new { style = "width: 100%;" })
                                    )
                                </td>
                            </tr>
                            <tr>
                                <td><label>Creator:</label></td>
                                <td>
                                    @(Html.Kendo().DropDownListFor(m => m.EventCreatorID)
                                          .DataValueField("ID")
                                          .DataTextField("Email")
                                          .DataSource(source =>
                                          {
                                              source.Read(read => { read.Action("DropDownUsers", "Dropdowns"); });
                                          })
                                          .Value(Model.EventCreatorID)
                                          .HtmlAttributes(new { style = "width:100%;" })
                                          .AutoBind(true)
                                          .Enable(false)
                                    )
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-sm-12">
                        <br /><br />
                        <div class="pull-right">
                            <input type="submit" value="Save" class="btn btn-inverse">
                            @if (Model.Complete == true)
                            {
                                <input type="submit" name="MarkNotComplete" value="Not Complete" class="btn btn-danger">
                            }
                            else
                            {
                                <input type="submit" name="MarkComplete" value="Complete" class="btn btn-success">
                                <input type="submit" name="MarkCompleteD1" value="Complete & Duplicate (+1d)" class="btn btn-info">
                                <input type="submit" name="MarkCompleteD7" value="Complete & Duplicate (+7d)" class="btn btn-primary">
                            }
                        </div>
                    </div>
                </div>
            }


        </div>
        <div class="col-md-6">
            <div>
                <div class="panel panel-default">
                    <div class="panel-heading div-inline" style="padding:0;;">
                        <h4>Event Histories</h4>
                    </div>
                    <div class="panel-body" style="padding:0; max-height: 500px; overflow-y:scroll;">
                        @(Html.Kendo().Grid<SnapSuite.Models.QuotationEventViewModel>()
                            .Name("GridEventHistories")
                            .HtmlAttributes(new { style = "min-width: 500px" })
                            .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Events").Empty("No Events Found")))
                            .Columns(columns =>
                            {
                                columns.Bound(p => p.Complete).Title("Status").ClientTemplate(
                                                                                "#if(Complete){ #<span class='glyphicon glyphicon-ok' title='Complete' style='color:green'></span> #}#"
                                                                                + "#if(!Complete && Overdue){ # <span class='label label-danger'> Overdue </span> #}#"
                                                                                + "#if(!Complete && Due){ # <span class='label label-warning'> Due </span> #}#"
                                                                            ).EditorTemplateName("CheckboxTemplate").Width("1%");
                                columns.Bound(p => p.Timestamp).Title("Date Due").Format("{0:HH:mm dd/MM/yyyy}").ClientTemplate("<span class='label label-info'>#=kendo.toString(Timestamp, 'HH:mm  dd/MM/yy')#</span>").Width("1%");
                                columns.Bound(p => p.ContactName).Title("Contact");
                                columns.Bound(p => p.Message).Title("Message");
                                //columns.Bound(p => p.Creator).Title("Created By").ClientTemplate("#=Creator.Email#").Width("1%");
                                columns.Template(@<text></text>).ClientTemplate("<a href='javascript:void(0)' onclick='EditEvent(\"#=ID#\")' title='Edit'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width("1%");
                            })
                            //.Sortable()
                            .DataSource(dataSource => dataSource
                                .Ajax()
                                //.Sort(sort => sort.Add("Timestamp").Descending()) // <-- initial sort expression
                                .Model(model =>
                                {
                                    model.Id(l => l.ID);
                                })
                                .Read(read => read.Action("Read", "QuotationEvents", new { quoteID = Model.QuotationID })).PageSize(10)
                                .Update(update => update.Action("Update", "QuotationEvents"))
                            )
                            .Events(events => events.DataBound("KendoGridDatabound"))
                        )
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PutneyAndWood/Views/Pipeline/_EditOpportunity.cshtml
@model SnapSuite.Models.OpportunityViewModel

@Html.Partial("_EditOpportunityDetails", Model)

<div>  
    <div class="col-sm-12">
        <br />
        @(Html.Kendo().TabStrip().Scrollable(false)
        .Name("Opportunity_Tabstrip")
        .Items(tabstrip =>
        {
            tabstrip.Add().Text("Events").Content(@Html.Partial("_EventsTab", Model).ToHtmlString()).Selected(true);
        }))
    </div>  
</div>

PutneyAndWood/Views/Pipeline/_EventsTab.cshtml
@model SnapSuite.Models.OpportunityViewModel

<script>
    function OnGridAssociativesRequestEnd(e) {
        if (e.type !== null && e.type !== 'read') {
            $("#GridAssociatives").data("kendoGrid").dataSource.read();
        }
    }

    function NewEvent() {
        $.ajax({
            url: '/Pipeline/_NewEvent',
            type: 'GET',
            data: {
                oppID: '@Model.ID'
            },
            success: function(response) {
                $('#Modal1 .modal-body').html(response);
                $('#Modal1').modal('show');
            }
        });
    }

    function EditEvent(id) {
        $.ajax({
            url: '/Pipeline/_EditEvent',
            type: 'GET',
            data: {
                eventID: id
            },
            success: function(response) {
                $('#Modal1 .modal-body').html(response);
                $('#Modal1').modal('show');
            }
        });
    }

    function OnSaveEventSuccess(e) {
        $('#GridEvents').data('kendoGrid').dataSource.read();
        if (e.Status == "Success") {
            if (e.CreateNew != null) {
                $.ajax({
                    url: '/Pipeline/_NewEvent',
                    type: 'GET',
                    data: {
                        oppID: '@Model.ID',
                        eventAssignedUserID: e.CreateNew.EventAssignedUserID,
                        clientID: e.CreateNew.ClientID,
                        contactID: e.CreateNew.ContactID,
                        timestamp: e.CreateNew.Timestamp,
                    },
                    success: function(response) {
                        $('#Modal1 .modal-body').html(response);
                        $('#Modal1').modal('show');
                    }
                });
            }
            else {
                $('#Modal1').modal('hide');
            }
        }
    }
</script>

<br />

@if (ViewBag.EditCRM)
            {
    <a class="btn btn-info btn-sm" onclick="NewEvent();" style="margin-bottom:5px;"><span class="glyphicon glyphicon-time"></span>&nbsp;New Event</a>
}
<a class="btn btn-default btn-sm" onclick="$('#GridEvents').data('kendoGrid').dataSource.read();" style="margin-bottom:5px; float:right"><span class="glyphicon glyphicon-refresh"></span>&nbsp;Refresh</a>


@(Html.Kendo().Grid<SnapSuite.Models.ClientEventViewModel>()
                .Name("GridEvents")
                .HtmlAttributes(new { style = "min-width: 900px" })
                .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Events").Empty("No Events Found")))
                .Columns(columns =>
                {
                    columns.Bound(p => p.Complete).Title("Status").ClientTemplate(
                                                                                "#if(Complete){ #<span class='glyphicon glyphicon-ok' title='Complete' style='color:green'></span> #}#"
                                                                                + "#if(!Complete && Overdue){ # <span class='label label-danger'> Overdue </span> #}#"
                                                                                + "#if(!Complete && Due){ # <span class='label label-warning'> Due </span> #}#"
                                                                            ).EditorTemplateName("CheckboxTemplate").Width("1%");
                    columns.Bound(p => p.Timestamp).Title("Date Due").Format("{0:HH:mm dd/MM/yyyy}").ClientTemplate("<span class='label label-info'>#=kendo.toString(Timestamp, 'HH:mm  dd/MM/yy')#</span>").Width("1%");
                    columns.Bound(p => p.Contact).Title("Contact").ClientTemplate("#=Contact.Name#").EditorTemplateName("EventContactDropDown");
                    columns.Bound(p => p.Message).Title("Message").EditorTemplateName("TextAreaTemplate");
                    columns.Bound(p => p.AssignedUser).Title("Assigned To").ClientTemplate("#=AssignedUser.Email#").EditorTemplateName("EventUserDropDown").Width("1%");
                    //columns.Bound(p => p.Creator).Title("Created By").ClientTemplate("#=Creator.Email#").Width("1%");
                    if (ViewBag.EditCRM)
                    {
                        columns.Template(@<text></text>).ClientTemplate("<a href='javascript:void(0)' onclick='EditEvent(\"#=ID#\")' title='Edit'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width("1%");
                    }
                    if (ViewBag.EditCRM)
                    {
                        columns.Command(command =>
                        {
                            command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn' title='Delete' />");
                        }
                        ).Width("1%");
                    }
                })
                //.Sortable()
                .DataSource(dataSource => dataSource
                    .Ajax()
                    //.Sort(sort => sort.Add("Timestamp").Descending()) // <-- initial sort expression
                    .Model(model =>
                    {
                        model.Id(l => l.ID);
                        model.Field(l => l.CompanyID).Editable(false);
                        model.Field(l => l.Complete).Editable(true).DefaultValue(false);
                        model.Field(l => l.Timestamp).Editable(true).DefaultValue(DateTime.Now);
                        model.Field(t => t.Client).DefaultValue(new SnapSuite.Models.SelectItemViewModel { ID = Model.ClientID, Name = "" });
                        model.Field(t => t.Contact).DefaultValue(new SnapSuite.Models.ContactItemViewModel { ID = Model.ClientContactID, ClientID = Model.ClientID, Name = "" });
                        model.Field(t => t.AssignedUser).DefaultValue(new SnapSuite.Models.UserItemViewModel { ID = ViewBag.CurrentUserID, Email = ViewBag.CurrentUserEmail });
                        model.Field(t => t.Creator).Editable(false).DefaultValue(new SnapSuite.Models.UserItemViewModel { ID = ViewBag.CurrentUserID, Email = ViewBag.CurrentUserEmail });
                        model.Field(t => t.OpportunityID).Editable(false).DefaultValue(Model.ID);
                    })
                    .Create(create => create.Action("Create", "OpportunityEvents"))
                    .Read(read => read.Action("Read", "OpportunityEvents", new { oppID = Model.ID })).PageSize(10)
                    .Update(update => update.Action("Update", "OpportunityEvents"))
                    .Destroy(destroy => destroy.Action("Destroy", "OpportunityEvents"))
                    .Events(events => events.RequestEnd("OnGridEventsRequestEnd"))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
)

<br />
<br />
<br />