PutneyAndWood/Controllers/Clients/ClientImportController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SnapSuite.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Data;
//using Fruitful.Import;
using System.Threading.Tasks;

namespace SnapSuite.Controllers
{
    [Authorize]
    public class ClientImportController : BaseController
    {

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            if (ViewBag.EditCRM == false)
                Response.Redirect("/");
        }

        // GET: ProductImport
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Clients");
        }

        public ActionResult UploadClients()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadClients(HttpPostedFileBase upload)
        {
            var importService = new ClientImportService(CurrentUser.CompanyID, CurrentUser.Id, new SnapDbContext());
            var result = importService.ImportExcelFile(upload);

            if (result.Success)
                ViewBag.SuccessMessage = string.Format("{0} Clients have been successfully imported.\n\nClients Updated: {1}\nClients Added: {2}", result.NumberCreated + result.NumberUpdated, result.NumberUpdated, result.NumberCreated);
            else
                ViewBag.ErrorMessage = result.Exception.Message;
            
            return View("UploadClients");
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadClientsAjax(HttpPostedFileBase upload)
        {
            var importService = new ClientImportService(CurrentUser.CompanyID, CurrentUser.Id, new SnapDbContext());
            var result = importService.ImportExcelFile(upload);

            var response = new JsonResponse();
            if (result.Success)
            {
                response.Success = true;
                response.Message = string.Format("{0} Clients have been successfully imported.\n\nClients Updated: {1}\nClients Added: {2}", result.NumberCreated + result.NumberUpdated, result.NumberUpdated, result.NumberCreated);
            }
            else
            {
                response.Success = false;
                response.Message = result.Exception.Message;
            }

            return Json(response);
        }

        public ActionResult UploadContacts()
        {
            return View("UploadClients");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadContacts(HttpPostedFileBase upload)
        {
            var importService = new ClientContactImportService(CurrentUser.CompanyID, CurrentUser.Id, new SnapDbContext());
            var result = importService.ImportExcelFile(upload);

            if (result.Success)
                ViewBag.SuccessMessage = string.Format("{0} Client Contacts have been successfully imported.\n\nClient Contacts Updated: {1}\nClient Contacts Added: {2}", result.NumberCreated + result.NumberUpdated, result.NumberUpdated, result.NumberCreated);
            else
                ViewBag.ErrorMessage = result.Exception.Message;
            
            return View("UploadClients");

        }

        public ActionResult UploadAddresses()
        {
            return View("UploadClients");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadAddresses(HttpPostedFileBase upload)
        {
            var importService = new ClientAddressImportService(CurrentUser.CompanyID, CurrentUser.Id, new SnapDbContext());
            var result = importService.ImportExcelFile(upload);

            if (result.Success)
                ViewBag.SuccessMessage = string.Format("{0} Client Addresses have been successfully imported.\n\nClient Addresses Updated: {1}\nClient Addresses Added: {2}", result.NumberCreated + result.NumberUpdated, result.NumberUpdated, result.NumberCreated);
            else
                ViewBag.ErrorMessage = result.Exception.Message;
            return View("UploadClients");
        }

    }
}

PutneyAndWood/Views/ClientImport/UploadClients.cshtml
@{
    ViewBag.Title = "Import Clients, Contacts & Addresses";
}

<div class="row">
    <div class="col-sm-12">
        @if (ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success">
                @Html.Raw(@ViewBag.SuccessMessage)
            </div>
        }
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">
                <strong>Error:</strong> @Html.Raw(@ViewBag.ErrorMessage)
            </div>
        }
        
        <div id="uploadProgress" class="panel panel-primary" style="display:none">
            <div class="panel-body">
                <h3>Upload in progress....</h3>
                <h4 style="color:gray">Please wait while your import is being processed.</h4>
            </div>
        </div>

    </div>

    <div class="col-sm-12">
        <h2>Import Clients, Contacts & Addresses</h2>
        <hr />
    </div>

    <div class="col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-body">
                @using (Html.BeginForm("UploadClients", "ClientImport", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <h3>Import Clients</h3>
                    <hr />
                    <lable><strong>Step 1. Download our Clients Template</strong></lable>
                    <p>First download our Excel template file. This file has the correct column headings needs to import your organisation data.</p>
                    <a class="btn btn-primary btn-xs" target="_blank" href="/Content/Import Clients Template.xls"><span class="glyphicon glyphicon-download-alt"></span>&nbsp;Download Template</a>
                    <br />
                    <br />
                    <lable><strong>Step 2. Copy your organisations into the template</strong></lable>
                    <p>Copy and Paste your existing organisations to the template file using an spreadsheet editor such us Microsoft Excel or Open Office Calc</p>                    
                    <br />
                    
                    <lable><strong>Step 3. Upload the updated template file</strong></lable>
                    <p>Simply select the file on your computer and press the import button below. The file should be in ".xls" format.</p>
                    <br />

                    <input id="upload" type="file" name="upload" accept=".xls" />
                    <hr />
                    <input type="submit" value="Upload Clients" class="btn btn-primary" onclick="ShowProgress()" />
                }
                @if (ViewBag.QuickBooks)
                {
                    <br />
                    using (Html.BeginForm("PopupImportCustomerFromQB", "Quickbooks", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From QuickBooks" class="btn btn-primary" onclick="if (!confirm('Import from QuickBooks?')) { return false; } ShowProgress()" />
                    }
                }
                @if (ViewBag.Xero)
                { 
                    <br />
                    using (Html.BeginForm("PopupImportCustomerFromXero", "Xero", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From Xero" class="btn btn-primary" onclick="if (!confirm('Import from Xero?')) { return false; } ShowProgress()" />
                    }
                }
                @if (ViewBag.HubSpot)
                {
                    <br />
                    using (Html.BeginForm("ImportFromHubSpot", "ClientImport", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From HubSpot" class="btn btn-primary" onclick="if (!confirm('Import clients along with their contacts from HubSpot?')) { return false; } ShowProgress()" />
                    }
                }
                @if (ViewBag.Insightly)
                {
                    <br />
                    using (Html.BeginForm("ImportFromInsightly", "ClientImport", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From Insightly" class="btn btn-primary" onclick="if (!confirm('Import clients along with their contacts from Insightly?')) { return false; } ShowProgress()" />
                    }
                }
                @if (ViewBag.Zoho)
                {
                    <br />
                    using (Html.BeginForm("ImportFromZoho", "ClientImport", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From Zoho" class="btn btn-primary" onclick="if (!confirm('Import clients along with their contacts from Zoho?')) { return false; } ShowProgress()" />
                    }
                }
                @if (ViewBag.Salesforce)
                {
                    <br />
                    using (Html.BeginForm("ImportFromSalesforce", "ClientImport", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From Salesforce" class="btn btn-primary" onclick="if (!confirm('Import clients along with their contacts from Salesforce?')) { return false; } ShowProgress()" />
                    }
                }
                @if (ViewBag.Infusionsoft)
                {
                    <br />
                    using (Html.BeginForm("ImportFromInfusionsoft", "ClientImport", null, FormMethod.Post, null))
                    {
                        <input type="submit" value="Import From Infusionsoft" class="btn btn-primary" onclick="if (!confirm('Import clients along with their contacts from Infusionsoft?')) { return false; } ShowProgress()" />
                    }
                }
            </div>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="panel panel-success">
            <div class="panel-body">
                @using (Html.BeginForm("UploadContacts", "ClientImport", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <h3>Import Client Contacts</h3>
                    <hr />
                    <lable><strong>Step 1. Download our Contacts Template</strong></lable>
                    <p>First download our Excel template file. This file has the correct column headings needs to import your contacts data.</p>
                    <a class="btn btn-success btn-xs" target="_blank" href="/Content/Import Contacts Template.xls"><span class="glyphicon glyphicon-download-alt"></span>&nbsp;Download Template</a>
                    <br />
                    <br />
                    <lable><strong>Step 2. Copy your contacts into the template</strong></lable>
                    <p>Copy and Paste your contacts to the template file using an spreadsheet editor such us Microsoft Excel or Open Office Calc</p>                    
                    <br />

                    <lable><strong>Step 3. Upload the updated template file</strong></lable>
                    <p>Simply select the file on your computer and press the import button below. The file should be in ".xls" format.</p>
                    <br />

                    <input id="upload" type="file" name="upload" accept=".xls" />
                    <hr />
                    <input type="submit" value="Upload Client Contacts" class="btn btn-success" onclick="ShowProgress()" />
                }
            </div>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="panel panel-info">
            <div class="panel-body">
                @using (Html.BeginForm("UploadAddresses", "ClientImport", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <h3>Import Client Addresses</h3>
                    <hr />
                    <lable><strong>Step 1. Download our Addresses Template</strong></lable>
                    <p>First download our Excel template file. This file has the correct column headings needs to import your addresses data.</p>
                    <a class="btn btn-info btn-xs" target="_blank" href="/Content/Import Addresses Template.xls"><span class="glyphicon glyphicon-download-alt"></span>&nbsp;Download Template</a>
                    <br />
                    <br />
                    <lable><strong>Step 2. Copy your addresses into the template</strong></lable>
                    <p>Copy and Paste your addresses to the template file using an spreadsheet editor such us Microsoft Excel or Open Office Calc</p>                    
                    <br />

                    <lable><strong>Step 3. Upload the updated template file</strong></lable>
                    <p>Simply select the file on your computer and press the import button below. The file should be in ".xls" format.</p>
                    <br />

                    <input id="upload" type="file" name="upload" accept=".xls" />
                    <hr />
                    <input type="submit" value="Upload Client Addresses" class="btn btn-info" onclick="ShowProgress()"/>
                }
            </div>
        </div>
    </div>
</div>

<script>
    function ShowProgress() {
        $("#uploadProgress").fadeIn();
    }
</script>