PutneyAndWood/Controllers/Quotations/QuotationPreviewController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SnapSuite.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;


namespace SnapSuite.Controllers
{
    [Authorize]
    public class QuotationPreviewController : ServiceGridController<QuotationPreviewItem, QuotationPreviewItemViewModel, QuotationPreviewItemService<QuotationPreviewItemViewModel>>
    {

        public QuotationPreviewController()
            : base(new QuotationPreviewItemService<QuotationPreviewItemViewModel>(Guid.Empty, null, null, new QuotationPreviewItemMapper(), new SnapDbContext()))
        {

        }

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.CheckSubscription();

            if (ViewBag.ViewQuotations == false)
                Response.Redirect("/");
        }
  
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Quotations");
        }
        
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")] 
        public ActionResult Edit(Guid ID)
        {
            this.CheckSubscription();
            var quoteService = new QuotationService<QuotationViewModel>(_service.CompanyID, _service.CurrentUserID, new QuotationMapper(), _service.DbContext);
            var model = quoteService.FindByID(ID);
            var viewModel = quoteService.MapToViewModel(model);
            
            return View(viewModel);
        }

        public override JsonResult Read([DataSourceRequest] DataSourceRequest request)
        {
            throw new NotImplementedException();
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public virtual JsonResult Read([DataSourceRequest] DataSourceRequest request, Guid ID)
        {
            var viewModels = _service.Read(ID).OrderBy(i => i.SortPos).ToList().Select(s => _service.MapToViewModel(s)).ToList();
            return Json(viewModels.ToDataSourceResult(request));
        }
        

        [AllowAnonymous]
        public ActionResult _GenerateQuotationPDF(Guid id, string checksum, bool download = false)
        {
            //try
            //{
                //Get PDF generation ready.
                string filename = "";
                string filePath = GeneratePDF(Server, id, checksum, ref filename);

                if (download) { return File(Server.MapPath(filePath), "application/pdf", filename); }
                else
                {
                    Response.AddHeader("Content-Disposition", string.Format("inline; filename={0};", filename.Replace(" ", "_")));
                    return File(Server.MapPath(filePath), "application/pdf");
                }
            //}
            //catch
            //{
            //    var pdfBytes = PDFService<QuotationPDFViewModel>.GenerateErrorPage();
            //    return File(pdfBytes, "application/pdf");
            //}
        }


        public ActionResult _EmailPDF(Guid ID)
        {            
            var settings = new QuotationSettingsService<EmptyViewModel>(null, null, _service.DbContext).FindByID(_service.CompanyID);
            var quoteService = new QuotationService<EmptyViewModel>(CurrentUser.CompanyID, CurrentUser.Id, null, _service.DbContext);
            var quote = quoteService.FindByID(ID);
            var emailTemplate = quoteService.GetEmailTitleMessage(quote.ID);

            var attachService = new QuotationAttachmentService<QuotationAttachmentViewModel>(_service.CompanyID, quote.ID, null, new QuotationAttachmentMapper(), _service.DbContext);
            var attachments = attachService.Read().Where(a => a.File.FileFormat != FileFormat.Link && a.File.FileSize <= (10 * 1024 * 1024)).Include(i => i.File).OrderBy(i => i.Filename).ToArray().Select(i => attachService.MapToViewModel(i)).ToList();
                
            var emailViewModel = new QuotationEmailViewModel
            {
                QuotationID = quote.ID.ToString(),
                ClientID = quote.ClientID.ToString(),
                CheckSum = quote.CheckSum,
                ToEmails = (quote.ClientContact != null && !string.IsNullOrWhiteSpace(quote.ClientContact.Email) ) ? quote.ClientContact.Email + ";" : "",
                FromEmail = (!string.IsNullOrWhiteSpace(settings.DefaultFromEmail)) ? settings.DefaultFromEmail : CurrentUser.Email,
                Bcc = CurrentUser.Email,
                Title = emailTemplate.Title,
                Message = emailTemplate.Body,
                IncludePDF = true,
                SendCopyPDF = true,
                Attachments = attachments,
                SelectedAttachments = attachments.Where(a => a.ShowInPreview == true).Select(a => a.ID.ToString()).ToArray()
            };

            return PartialView(emailViewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _EmailPDF(QuotationEmailViewModel model)
        {
            try
            {
                List<string> sentEmails = new List<string>();
                List<string> failEmails = new List<string>();

                var quoteService = new QuotationService<QuotationViewModel>(CurrentUser.CompanyID, CurrentUser.Id, new QuotationMapper(), _service.DbContext);
                quoteService.EmailPDF(Guid.Parse(model.QuotationID),
                                        model.Title,
                                        model.Message,
                                        model.FromEmail,
                                        model.ToEmails.Replace(" ", "").Split(';').Where(s => !string.IsNullOrWhiteSpace(s)).ToArray(),
                                        null,
                                        model.IncludePDF,
                                        (model.SendCopyPDF) ? CurrentUser.Id : "",
                                        (model.SelectedAttachments != null) ? model.SelectedAttachments.Select(i => Guid.Parse(i)).ToList() : null,
                                        ref sentEmails, ref failEmails);

                string output = "";

                if (sentEmails.Count() > 0)
                {
                    output += "Quotation has successfully been emailed to: \n";
                    output += string.Join("\n", sentEmails);
                    output += Environment.NewLine;
                }

                if (failEmails.Count() > 0)
                {
                    output += "Failed to send Quotation to: \n";
                    output += string.Join("\n", failEmails);
                }

                return JavaScript("EmailSent('" + HttpUtility.JavaScriptStringEncode(output) + "'); HideViews();");
            }
            catch(Exception ex) { return JavaScript("EmailSent('" + HttpUtility.JavaScriptStringEncode(ex.Message) + "'); HideViews();"); }
        }


        [AllowAnonymous]
        public ActionResult Review(Guid ID, string Jasq = "")
        {
            return RedirectToAction("Index", "QuotationReview", new { ID = ID, Jasq = Jasq });
        }


        public ActionResult _PDF(Guid id, string checksum)
        {
            ViewBag.ID = id;
            ViewBag.CheckSum = checksum;
            return PartialView();
        }


        public ActionResult _PdfSize(Guid id)
        {
            try
            {
                var filepath = FileService.GetUploadPhysicalFilePath(_service.CompanyID, "/_Temp/", id.ToString() + ".pdf");
                long length = new System.IO.FileInfo(filepath).Length;
                return Content(FileEntryExtension.FileSizeToLabel((int)new System.IO.FileInfo(filepath).Length));
            }
            catch { return Content("ERROR"); }            
        }


        public string GeneratePDF(HttpServerUtilityBase server, Guid id, string checksum, ref string filename)
        {
            var quoteService = new QuotationService<QuotationViewModel>(Guid.Empty, null, new QuotationMapper(), _service.DbContext);
            var quote = quoteService.Read(Guid.Empty).Where(i => i.ID == id && i.CheckSum == checksum).First();
            var pdfService = new QuotationPdfGenService(quote.CompanyID, null, _service.DbContext);
            filename = pdfService.GetPdfFilename(quote);
            return pdfService.GetDownloadUrl(quote);
        }


        [HttpPost]
        public ActionResult _UpdateItemPositions(Guid itemID, int oldIndex, int newIndex)
        {
            _service.UpdatePositions(itemID, oldIndex, newIndex);
            return Json("Success");
        }


        public JsonResult DropDownQuotationPreviewItem(Guid ID, PreviewItemType Type)
        {
            if(Type == PreviewItemType.Template)
            {   
                var list = new QuotationTemplateRepository().Read()
                    //.Where(p => (p.CompanyID == CurrentUser.CompanyID || p.CompanyID == null))
                    .Where(p => (p.CompanyID == CurrentUser.CompanyID))
                    .OrderBy(o => o.Type)
                    .ThenBy(o => o.Filename)
                    .ToList()
                    .Select(p => new SelectPreviewItemViewModel { OrderID = ID, TemplateAttachmentID = p.ID, Name = string.Format("({0}) {1}", p.Type.ToString(), p.Filename), Type = PreviewItemType.Template });

                return Json(list, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var list = new QuotationAttachmentService<EmptyViewModel>(_service.CompanyID, ID, null, null, _service.DbContext).Read()
                    .Where(p => p.File.FileFormat == FileFormat.Docx || p.File.FileFormat == FileFormat.Pdf)
                    .OrderBy(o => o.Filename)
                    .ToList()

PutneyAndWood/Views/QuotationPreview/Edit.cshtml
@model SnapSuite.Models.QuotationViewModel
@{
    ViewBag.Title = string.Format("Preview Estimate: {0}{1}", Model.Reference ?? "", Model.Number);
}


<div id="Div_EmailSent" class="row" style="display:none">
    <div class="col-sm-12">
        <div class="alert alert-warning " role="alert">
            <button type="button" class="close" onclick="$('#Div_EmailSent').css('display', 'none');"><span aria-hidden="true">&times;</span></button>
            <label id="Label_EmailSent" style="white-space:pre-line" ></label>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-8">
        <h1 style="display:inline-block">@ViewBag.Title</h1>
    </div>
    <div class="col-sm-4 hidden-xs">
        <br />
        <a class="btn btn-default" href="@Url.Action("Edit", "Quotations", new { ID = Model.ID })" style="float:right"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Back to Estimate</a>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <hr />
    </div>
    <div class="col-sm-12">        
        @*<button id="Button_Email" class="btn btn-info" onclick="Email()"><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;Email</button>*@
        <a id="Button_Download" class="btn btn-success" target="_blank" href="@Url.Action("_GenerateQuotationPDF", new { id = Model.ID, checksum = Model.CheckSum, download = true })"><span class="glyphicon glyphicon-download"></span>&nbsp;&nbsp;Download</a>        
    </div>
    @*<div class="col-sm-6">        
        <div class="input-group" style="max-width:none; width:100%">
            <input class="form-control" style="max-width:none; cursor: text;" type="text" readonly="readonly" value="@string.Format("{0}/QuotationReview/?ID={1}&Jasq={2}", this.Request.Url.GetLeftPart(UriPartial.Authority), Model.ID, Model.CheckSum)">
            <span class="input-group-btn">
                <a class="btn btn-primary" target="_blank" href="@string.Format("{0}/QuotationReview/?ID={1}&Jasq={2}", this.Request.Url.GetLeftPart(UriPartial.Authority), Model.ID, Model.CheckSum)">Review Link</a>
            </span>
        </div>
    </div>*@
    @*@if (ViewBag.EditQuotations)
    {
        <div class="col-sm-5">
            @Html.Partial("_EditPages", Model)
        </div>
    }*@   
    
    <div id="divPDF" class="col-sm-12">
        @Html.Action("_PDF", new { id = Model.ID, checksum = Model.CheckSum })
    </div>

</div>

<a id="Button_Close_Content" class="btn btn-background" onclick="HideViews()" style="z-index:1105; display:none;"></a>

@if (ViewBag.EditQuotations)
{
    <div id="SlideContent_Email" class="panel panel-default" style="z-index: 2010; position: fixed; overflow-y:scroll; margin: 0; top: 0; bottom:0; right: 0%; min-height: 100%; width: 0%; max-width: 600px; display: none;">
        <div class="panel-body" style="margin-top: 10px;">
            @Html.Action("_EmailPDF", Model)
        </div>
    </div>
}


<script>

    function Refresh(){
        RefreshGrid();
        RefreshPDF();
    }

    function RefreshGrid(){
        $("#GridPreviewItems").data('kendoGrid').dataSource.read();
    }

    function RefreshPDF() {
        $("#divPDF").load('@Url.Action("_PDF", new { id = Model.ID, checksum = Model.CheckSum })');
    }

    function Email() {
        $("#SlideContent_Email").animate({ width: '80%' }, { queue: false, duration: 300 });
        $("#SlideContent_Email").fadeIn();
        $("#Button_Close_Content").fadeIn();
        $("#divPDF").fadeOut();
        $("#span_EmailSize").load('@(Url.Action("_PdfSize", "QuotationPreview", new { ID = Model.ID }))');
    }

    function HideViews() {
        $("#SlideContent_Email").animate({ width: '0%' }, { queue: false, duration: 300 });
            setTimeout(function () {
            $("#SlideContent_Email").fadeOut();
            $("#Button_Close_Content").fadeOut();
            $("#divPDF").fadeIn();
            }, 300);
    }

    function GetDropdownSearchInfo() {

        var grid = $("#GridPreviewItems").data("kendoGrid");
        var dataItem = grid.dataItem(grid.tbody.find(">tr.k-grid-edit-row"));

        var SearchValues = {
            ID: '@Model.ID',
            Type: dataItem.get("Type"),
        };

        return SearchValues;
    }


</script>

PutneyAndWood/Views/QuotationPreview/_EditPages.cshtml
@model SnapSuite.Models.QuotationViewModel

<br />
<br />
<div class="panel panel-default">
    <div class="panel-body">
        <h3>Quotation Creation</h3>
        <p>Select the templates & attachments for your Quotation.</p>
        @if (User.IsInRole("Super Admin"))
        {
            <p><a href="@Url.Action("Index", "QuotationTemplates")">Click here to create and upload your own templates.</a></p>
        }
        <hr />
        @*<a class="btn btn-info btn-xs" onclick="$('#GridPreviewItems').data('kendoGrid').addRow(); return false;" style="margin-bottom:5px;"><span class="glyphicon glyphicon-plus"></span>&nbsp;Add Page</a>*@
        @(Html.Kendo().Grid<SnapSuite.Models.QuotationPreviewItemViewModel>()
                .Name("GridPreviewItems")
                //.Pageable(p => p.Messages(m => m.Display("{0} - {1} of {2} Templates/Attachments").Empty("No Pages/Attachments Added")))
                .Columns(columns =>
                {
                    columns.Bound(u => u.ID).Title(" ").ClientTemplate("<span class='fa fa-sort glyphicon-btn' style='cursor:move'></span>").HtmlAttributes(new { @class = "sortable-cell" }).EditorTemplateName("BlankTemplate").Width("1%");
                    columns.Bound(a => a.Type).ClientTemplate("#if(Type== 'Attachment'){# <span class='label label-danger'>#} else{# <span class='label label-info'>#}# #=Type#</span>").EditorTemplateName("TemplateTypeDropDown").Title("Type").Width("1%");
                    columns.Bound(a => a.TemplateAttachment).ClientTemplate("#if(TemplateAttachment != null){# #=TemplateAttachment.Name# #}#").EditorTemplateName("TemplateAttachmentDropDown").Title("Name");
                    columns.Command(command =>
                    {
                        command.Edit().Text("<span class='glyphicon glyphicon-edit glyphicon-btn' title='Edit' />").UpdateText("<span class='glyphicon glyphicon-ok glyphicon-btn' title='Ok' />").CancelText("<span class='glyphicon glyphicon-remove glyphicon-btn' title='Cancel' />");
                        //command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn' title='Delete' />");
                    }
                    ).Width("80px");
                })
                .Editable(editable => editable.Mode(GridEditMode.InLine).CreateAt( GridInsertRowPosition.Bottom).ConfirmDelete("Are you sure you want to delete this page?"))
                //.Sortable()
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Model(model =>
                    {
                        model.Id(a => a.ID);
                        model.Field(a => a.ID).Editable(false);
                        model.Field(a => a.ParentID).Editable(false).DefaultValue(Guid.Parse(Model.ID));
                        model.Field(a => a.Type).Editable(true).DefaultValue("Template");
                        model.Field(a => a.TemplateAttachment).DefaultValue(new SnapSuite.Models.SelectPreviewItemViewModel { OrderID = Guid.Parse(Model.ID) });
                    })
                    .Create(create => create.Action("Create", "QuotationPreview"))
                    .Read(read => read.Action("Read", "QuotationPreview", new { ID = Model.ID }))
                    .Update(update => update.Action("Update", "QuotationPreview"))
                    .Destroy(destroy => destroy.Action("Destroy", "QuotationPreview"))
                    .Events(events => events.RequestEnd("OnGridItemsRequestEnd"))
                )
        //.Events(events => events.DataBound("KendoGridDatabound"))
        //.AutoBind(true)
        )
        <br />
        <br />
        @*<a href="@Url.Action("Business", "Settings")">Edit business name, address & logo</a>*@
    </div>

    <script>
        $(".k-grid[id='GridPreviewItems'] table").kendoSortable({
            filter: ">tbody >tr:not('.k-grid-edit-row')", ignore: "td:not('.sortable-cell'), td:not('.sortable-cell') *",
            disabled: ".no-drag", //do not allow transferring the no records row
            hint: $.noop,
            cursor: "move",
            placeholder: function (element) {
                return element.clone().addClass("k-state-hover").css("opacity", 0.65);
            },
            change: function (e) { //change event handler implementation may differ according to the scenario
                //var grid = this.element.closest(".k-grid").data("kendoGrid");
                var dataItem = $('#GridPreviewItems').data('kendoGrid').dataSource.getByUid(e.item.data("uid"));
                $.ajax({
                    url: '@Url.Action("_UpdateItemPositions", "QuotationPreview")',
                    type: 'POST',
                    data: {
                        itemID: dataItem.ID,
                        oldIndex: e.oldIndex,
                        newindex: e.newIndex,
                    },
                    dataType: "json",
                    success: function (data) { Refresh(); }
                });
            },
            move: function (e) { }
        });


        function OnGridItemsRequestEnd(e) {
            //RequestEnd handler code
            if (e.type !== null && e.type !== 'read') {
                Refresh();
            }
        }

    </script>
</div>

PutneyAndWood/Views/QuotationPreview/_EmailPDF.cshtml
@model SnapSuite.Models.QuotationEmailViewModel


@using (Ajax.BeginForm("_EmailPDF", "QuotationPreview", null, new AjaxOptions { }, new { enctype = "multipart/form-data", method = "post", onsubmit = "SendEmail()" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.QuotationID)
    @Html.HiddenFor(model => model.ClientID)
    @Html.HiddenFor(model => model.CheckSum)    
    <div class="row">
        <div class="col-xs-9">
            <h3>Email Quotation</h3>
        </div>
        <div class="col-xs-3">
            <br />
            <a class="btn btn-sm btn-default" onclick="HideViews(); return false;" style="float:right;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
        </div>
        <div class="col-xs-12">
            <hr />
            <label>To:</label><br />
            @(Html.Kendo().AutoCompleteFor(model => model.ToEmails)
                .DataTextField("Name") //Specify which property of the Product to be used by the MultiSelect as a text.
                .Placeholder("Enter emails addresses...")
                .Separator("; ")
                .ClearButton(false)
                //.AutoBind(true)
                .DataSource(source =>
                    {
                        source.Read(read =>
                        {
                            read.Action("DropdownClientEmails", "Clients").Data("function() { return { cltID: '" + @Model.ClientID + "'}}");
                        });
                    })
                .HtmlAttributes(new { style = "width: 100%; max-width: none;" })
            )
            <span style="font-size:x-small">Use the seperator '; ' to add multiple emails.</span><br />
            @Html.ValidationMessageFor(model => model.ToEmails, "", new { @class = "text-danger" })

            <br />
            <label>From:</label>
            @Html.TextBoxFor(model => model.FromEmail, new { @class = "form-control", @style = "max-width:none" })
            @Html.ValidationMessageFor(model => model.FromEmail, "", new { @class = "text-danger" })
            <br />
            <label>Title:</label><br />
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @style = "max-width:none" })<br />

            @*<label>Message:</label><br />
            @Html.TextAreaFor(model => model.Message, new { @class = "form-control", @style = "max-width:none", @rows = 5 })<br />*@
            @(Html.Kendo().EditorFor(model => model.Message)
                          .HtmlAttributes(new { @style = "max-width: none;", @aria_label = "editor", @class = "form-control" })
                          .Resizable(resizable => resizable.Content(true))
                          .Tools(
                              tools => tools.FontName()
                                            .FontColor()
                                            .FontSize()
                                            .BackColor()
                          )
                          .Messages(messages => messages.FontSizeInherit("(font size)")
                                                        .FontNameInherit("(font family)"))
            )
            <br />
            <div class="checkbox">
                @Html.CheckBoxFor(model => model.IncludePDF) &nbsp;<strong>Include quotation as PDF attachment? (<span id="span_EmailSize">0Kbs</span>)</strong>
            </div>
            <div class="checkbox">
                @Html.CheckBoxFor(model => model.SendCopyPDF) &nbsp;<strong>Send copy to @Model.Bcc?</strong>
            </div>
            @if (Model.Attachments.Count() > 0)
            {
                <div class="panel panel-default">
                    <div class="panel-body">                        
                        <label>Attachments to include:</label>
                        <hr />
                        @foreach (var item in Model.Attachments)
                        {
                            <div class="checkbox">
                                @if (Model.SelectedAttachments.Contains(item.ID))
                                {
                                    <text>
                                    <input name="SelectedAttachments" type="checkbox" value="@item.ID" checked="checked" /> &nbsp;<strong>@item.Filename (@item.File.FileSize)</strong>
                                    </text>
                                }
                                else
                                {
                                    <text>
                                    <input name="SelectedAttachments" type="checkbox" value="@item.ID" /> &nbsp;<strong>@item.Filename (@item.File.FileSize)</strong>
                                    </text>
                                }
                            </div>
                        }                        
                    </div>                    
                </div>                
            }
            <span style="font-size:smaller">Max 10Mbs Attachment size.</span>
            <hr />
            <input type="submit" value="Send Email" class="btn btn-success" onclick="SendEmail();" />
            <div id="Div_SendingEmail" style="display:none;" ><span><strong>&nbsp;&nbsp;Sending Email....</strong></span></div>
        </div>

    </div>
    

    <script>
        $("#ToEmails").on("focus", function () {
            var autocomplete = $("#ToEmails").data("kendoAutoComplete");
            autocomplete.dataSource.read();
            autocomplete.popup.open();
        });

        function SendEmail() {

            if (this.valid()) {
                $("#Div_SendingEmail").show();
            }
        }

        
        function EmailSent(message) {            
            $("#Div_SendingEmail").hide();
            $("#Div_EmailSent").fadeIn();
            $("#Label_EmailSent").text(message);
            HideViews();
        }
        
    </script>

    
}

PutneyAndWood/Views/QuotationPreview/_PDF.cshtml
<hr />
@if (!Request.UserAgent.ToLower().Contains("iphone") && !Request.UserAgent.ToLower().Contains("ipad"))
{
    <div>
        <object class="pdf-scroller" data="@Url.Action("_GenerateQuotationPDF", new { id = ViewBag.ID, checksum = ViewBag.CheckSum, random = DateTime.Now })" type="application/pdf" style="width:100%; height:1000px">
            <div class="alert alert-danger" role="alert"><strong><span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Unable to load PDF Preview. Please make sure your browser has a PDF viewer plugin installed.</strong></div>
        </object>
    </div>
}
else
{
    <div class="panel panel-default">
        <div class="panel-body" style="margin-top:75px; margin-bottom:75px; text-align:center">
            <a class="btn btn-lg btn-success" href="@Url.Action("_GenerateQuotationPDF", new { id = ViewBag.ID, checksum = ViewBag.CheckSum })" style="display:block; margin-left:auto; margin-right:auto; max-width:300px;">
                <span class="glyphicon glyphicon-cloud-download"></span>&nbsp;&nbsp;Download PDF
            </a>
            <br />
            <label>Your browser does not support embedded PDFs. Please click the button above to download the PDF.</label>
        </div>
    </div>
}