PutneyAndWood/Controllers/Quotations/QuotationReviewController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SnapSuite.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;


namespace SnapSuite.Controllers
{
    [AllowAnonymous]
    public class QuotationReviewController : ServiceEntityController<Quotation, QuotationClientViewModel, QuotationService<QuotationClientViewModel>>
    {

        public QuotationReviewController()
            : base(new QuotationService<QuotationClientViewModel>(Guid.Empty, null, new QuotationClientMapper(), new SnapDbContext()))
        {

        }        
  
        public ActionResult Index(Guid? ID = null, string Jasq = "", string errorMessage = null)
        {   
            var model = _service.Read(Guid.Empty)
                                .Where(i => i.ID == ID && i.CheckSum == Jasq && i.IsClientVersion == false)
                                .Include(i => i.Company)
                                .Include(i => i.Attachments)
                                .DefaultIfEmpty(null)
                                .FirstOrDefault();

            if(model == null) return RedirectToAction("Index", "Home");

            var viewModel = _service.MapToViewModel(model);
            SetCustomTheme(model.Company);
            SetNoNavBar();

            var draft =  new GenericService<Quotation>(_service.DbContext).Read().Where(i => i.MainVersionID == ID && i.IsClientVersion == true && i.IsClientDraft == true).DefaultIfEmpty(null).FirstOrDefault();
            if (draft != null)
            {
                ViewBag.SavedDraftID = draft.ID;
                ViewBag.SavedDraftCheckSum = draft.CheckSum;
            }
            
            ViewBag.ErrorMessage = errorMessage;

            return View(viewModel);
        }


        public ActionResult CreateCustomize(Guid? ID = null, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty).Where(i => i.ID == ID && i.CheckSum == Jasq).DefaultIfEmpty(null).FirstOrDefault();
            if (model == null) return RedirectToAction("Index", new { ID = ID, Jasq = Jasq });

            _service.CompanyID = model.CompanyID;
            var newOrder = _service.Version(ID.Value, null, true);

            return RedirectToAction("Customize", new { ID = newOrder.ID, Jasq = newOrder.CheckSum });
        }


        public ActionResult ResetCustomize(Guid? ID = null, string Jasq = "", Guid? MainID = null)
        {
            var model = _service.Read(Guid.Empty).Where(i => i.ID == ID && i.CheckSum == Jasq).DefaultIfEmpty(null).FirstOrDefault();
            var main = _service.Read(Guid.Empty).Where(i => i.ID == MainID).DefaultIfEmpty(null).FirstOrDefault();
            if (model == null || main == null) return RedirectToAction("Index", "Home");

            //Destroy current client version
            _service.CompanyID = model.CompanyID;
            _service.Destroy(model);

            //Then current a new one.
            var newOrder = _service.Version(main.ID, null, true);

            return RedirectToAction("Customize", new { ID = newOrder.ID, Jasq = newOrder.CheckSum });
        }

        public ActionResult SubmitCustomizeForReview(Guid? ID = null, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty).Where(i => i.ID == ID && i.CheckSum == Jasq).DefaultIfEmpty(null).FirstOrDefault();
            if (model == null) return RedirectToAction("Index", "Home");

            var newOrder = _service.SubmitClientVersionForReview(model);
            return RedirectToAction("SubmitComplete", new { ID = newOrder.ID });
        }
        


        public ActionResult Customize(Guid? ID = null, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty)
                                .Where(i => i.ID == ID && i.CheckSum == Jasq)
                                .Include(i => i.Company)
                                .Include(i => i.Attachments)
                                .DefaultIfEmpty(null)
                                .FirstOrDefault();

            if (model == null) return RedirectToAction("Index", "Home");
            if (!model.IsClientVersion || !model.IsClientDraft) return RedirectToAction("Index", new { ID = ID, Jasq = Jasq });

            var viewModel = _service.MapToViewModel(model);
            SetCustomTheme(model.Company);
            SetNoNavBar();

            return View(viewModel);
        }

        public ActionResult DeleteCustomize(Guid? ID = null, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty).Where(i => i.ID == ID && i.CheckSum == Jasq && i.IsClientVersion && i.IsClientDraft).DefaultIfEmpty(null).FirstOrDefault();
            var mainModel = _service.Read(Guid.Empty).Where(i => i.ID == model.MainVersionID).Include(i => i.Company).DefaultIfEmpty(null).FirstOrDefault();
            if (model == null) return RedirectToAction("Index", "Home");

            _service.Destroy(model);
            
            if (mainModel != null) return RedirectToAction("Index", new { ID = mainModel.ID, Jasq = mainModel.CheckSum });
            else return RedirectToAction("Index", "Home");
        }


        public ActionResult SubmitComplete(string ID)
        {
            var model = _service.Read(Guid.Empty)
                                .Where(i => i.ID.ToString() == ID)
                                .Include(i => i.Company)
                                .DefaultIfEmpty(null)
                                .FirstOrDefault();

            try
            {
                SetCustomTheme(model.Company);
                SetNoNavBar();
            }
            catch { }            
            return View();
        }


        public ActionResult _HeaderURL(Guid ID, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty).Where(i => i.ID == ID && i.CheckSum == Jasq).DefaultIfEmpty(null).FirstOrDefault();
            var viewModel = _service.MapToViewModel(model);
            return PartialView("_Header", viewModel);
        }

        public ActionResult _Header(QuotationClientViewModel viewModel)
        {
            return PartialView(viewModel);
        }
        
        public ActionResult _ItemsURL(Guid ID, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty).Where(i => i.ID == ID && i.CheckSum == Jasq).DefaultIfEmpty(null).FirstOrDefault();
            var viewModel = _service.MapToViewModel(model);
            return PartialView("_Items", viewModel);
        }


        public ActionResult _Items(QuotationClientViewModel viewModel)
        {
            return PartialView(viewModel);
        }


        public ActionResult _SectionTotal(Guid sectionID)
        {
            var secService = new QuotationSectionService<QuotationSectionClientViewModel>(Guid.Empty, null, null, new QuotationSectionClientMapper(), _service.DbContext);
            var model = secService.FindByID(sectionID);
            var viewModel = secService.Mapper.MapToViewModel(model);
            return PartialView(viewModel);
        }

        public ActionResult _ItemImage(Guid id)
        {
            ViewBag.ID = id;
            return PartialView();
        }


        [AllowAnonymous]
        public ActionResult _AcceptReject(Guid ID, string Jasq = "")
        {
            var model = _service.Read(Guid.Empty)
                                .Where(i => i.ID == ID && i.CheckSum == Jasq)
                                .DefaultIfEmpty(null)
                                .FirstOrDefault();

            if (model == null) return RedirectToAction("Index", "Home");
                        
            var viewModel = new QuotationAcceptDeclineViewModel
            {
                QuotationID = model.ID.ToString(),
                CheckSum = model.CheckSum,
                StatusID = model.Status.ID,
                StatusName = model.Status.Name,
                StatusDescription = model.Status.Description,
                StatusHexColour = model.Status.HexColour,
            };
            return PartialView(viewModel);
        }


        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _AcceptReject(QuotationAcceptDeclineViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            if (!viewModel.Accept)
            {
                ViewBag.ErrorMessage = "Please select 'Accept'";
                return PartialView(viewModel);
            }

            var quoteService = new QuotationService<QuotationViewModel>(Guid.Empty, null, new QuotationMapper(), _service.DbContext);
            var quote = quoteService.FindByID(Guid.Parse(viewModel.QuotationID));

            quoteService.AcceptOrder(quote.ID, QuotationStatusValues.ACCEPTED, viewModel.Name, viewModel.Message, viewModel.PoNumber);
            return PartialView("_AcceptRejectComplete");
        }



        public ActionResult CompleteStripePayment(Guid ID, string Jasq = "", string stripeToken = "")
        {
            var model = _service.Read(Guid.Empty)
                                .Where(i => i.ID == ID && i.CheckSum == Jasq)
                                .DefaultIfEmpty(null)
                                .FirstOrDefault();

            if (model == null) return RedirectToAction("Index", "Home", new { errrorMessage = "Unable to complete payment. Quotation record not found." });
                        
            try
            {                
                var paymentService = new QuotationStripePaymentService<EmptyViewModel>(Guid.Empty, null, null, _service.DbContext);
                paymentService.CompleteChargePayment(model.ID, stripeToken);
                return RedirectToAction("Index", new { ID = ID, Jasq = Jasq });
            }

PutneyAndWood/Views/QuotationReview/Index.cshtml
@using SnapSuite.Models
@model QuotationClientViewModel
@{
    ViewBag.Title = string.Format("Quotation: {0}", Model.Reference);
}
<script src="https://js.stripe.com/v3/"></script>


<div class="row">
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            <strong>Error:</strong> @ViewBag.ErrorMessage
        </div>
    }
    <div class="col-sm-8">
        <h1 style="display:inline-block">@ViewBag.Title</h1>
    </div>
    <div class="col-sm-4">
        <br />

        <a id="Button_Download" class="btn btn-inverse hidden-xs" style="float:right; margin: 4px;" target="_blank" href="@Url.Action("_GenerateQuotationPDF", "QuotationPreview", new { id = Model.ID, checksum = Model.CheckSum, download = true })"><span class="glyphicon glyphicon-download"></span>&nbsp;&nbsp;Download</a>
        <a id="Button_Download" class="btn btn-inverse visible-xs" style="margin: 4px;" target="_blank" href="@Url.Action("_GenerateQuotationPDF", "QuotationPreview", new { id = Model.ID, checksum = Model.CheckSum, download = true })"><span class="glyphicon glyphicon-download"></span>&nbsp;&nbsp;Download</a>
                
        @if (!Model.HasAgreement && Model.StatusID <= SnapSuite.Models.QuotationStatusValues.ACCEPTED)
        {
            <a id="Button_SignAgreement" href="#" class="btn btn-success hidden-xs" style="float:right; margin: 4px;" onclick="SubmitAgreement()" ><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Accept Quotation</a>
            <a id="Button_SignAgreement" href="#" class="btn btn-success visible-xs" style="margin: 4px;" onclick="SubmitAgreement()" ><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Accept Quotation</a>
        }

        @if (ViewBag.SavedDraftID != null && ViewBag.SavedDraftCheckSum != null && Model.StatusID < SnapSuite.Models.QuotationStatusValues.ACCEPTED)
        {
            <a id="Button_Customize" class="btn btn-info hidden-xs" style="float:right; margin: 4px;" href="@Url.Action("Customize", new { ID = ViewBag.SavedDraftID, Jasq = ViewBag.SavedDraftCheckSum })"><span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Saved Customized Quotation</a>
            <a id="Button_Customize" class="btn btn-info visible-xs" style="margin: 4px;" href="@Url.Action("Customize", new { ID = ViewBag.SavedDraftID, Jasq = ViewBag.SavedDraftCheckSum })"><span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Saved Customized Quotation</a>
        }
        else if ((Model.AllowClientEditLineItems || Model.AllowClientEditSections) && Model.StatusID < SnapSuite.Models.QuotationStatusValues.ACCEPTED)
        {
            <a id="Button_Customize" class="btn btn-warning hidden-xs" style="float:right; margin: 4px;" href="@Url.Action("CreateCustomize", new { ID = Model.ID, Jasq = Model.CheckSum })"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Customize Quotation</a>
            <a id="Button_Customize" class="btn btn-warning visible-xs" style="margin: 4px;" href="@Url.Action("CreateCustomize", new { ID = Model.ID, Jasq = Model.CheckSum })"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Customize Quotation</a>
        }
    </div>
</div>
@if (Model.StatusID >= SnapSuite.Models.QuotationStatusValues.ACCEPTED || Model.StripeIsPaid)
{
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-success">
                <div class="panel-heading" style="text-align:center">
                    <h4 style="color:@Model.StatusHexColour">@Model.StatusDescription</h4>
                </div>
                @if (Model.StatusID >= SnapSuite.Models.QuotationStatusValues.ACCEPTED && Model.StripePaymentEnabled && !Model.StripeIsPaid && !Model.NeedsCheckedClientSubmission)
                {
                    <div class="panel-body" style="text-align:center">
                        <h3>@((!string.IsNullOrEmpty(Model.StripeDescription)) ? Model.StripeDescription : "Quotation Payment") Payment</h3>
                        <h4 class="grey-text">Make the payment of @(string.Format("{0}{1:#,##0.00}", Model.CurrencySymbol, Model.StripeAmount)) using your credit or debit card. </h4>
                        <form action="@Url.Action("CompleteStripePayment", "QuotationReview")" method="POST">
                            @Html.Hidden("ID", Model.ID)                            
                            @Html.Hidden("Jasq", Model.CheckSum)
                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="@Model.StripeKey"
                                    data-amount="@string.Format("{0}", (int)(Model.StripeAmount * 100m))"
                                    data-name="@Model.CompanyName"
                                    data-description="@Model.StripeDescription"
                                    data-image="@Model.CompanyImageURL"
                                    data-locale="auto"
                                    data-currency="@Model.StripeCurrency"
                                    data-billing-address="true"
                                    data-zip-code="true">
                            </script>
                        </form>
                    </div>
                }
                else if (Model.StripeIsPaid && !Model.NeedsCheckedClientSubmission)
                {
                    <div class="panel-body" style="text-align:center">
                        <h3>@((!string.IsNullOrEmpty(Model.StripeDescription)) ? Model.StripeDescription : "Quotation Payment") Paid</h3>
                        <h5 class="grey-text">A payment of @(string.Format("{0}{1:#,##0.00}", Model.CurrencySymbol, Model.StripeAmount)) was made on @Model.StripeCreated</h5>
                    </div>
                }
            </div>
        </div>
    </div>
}




<div id="divPDFView" class="row">
    <div class="col-sm-12">
        <hr /> 
    </div> 
    
    <div class="@((Model.Attachments.Count > 0) ? "col-sm-8" : "col-sm-12")"> 

        @if (!Request.UserAgent.ToLower().Contains("iphone") && !Request.UserAgent.ToLower().Contains("ipad"))
        {
            <object class="pdf-scroller" data="@Url.Action("_GenerateQuotationPDF", "QuotationPreview", new { id = Model.ID, checksum = Model.CheckSum })" type="application/pdf" style="width:100%; height:1000px">
                <div class="alert alert-danger" role="alert"><strong><span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Unable to load PDF Preview. Please make sure your browser has a PDF viewer plugin installed.</strong></div>
            </object>
        }
        else
        {
            <div class="panel panel-default">
                <div class="panel-body" style="margin-top:75px; margin-bottom:75px; text-align:center">
                    <a class="btn btn-lg btn-success" href="@Url.Action("_GenerateQuotationPDF", "QuotationPreview", new { id = Model.ID, checksum = Model.CheckSum })" style="display:block; margin-left:auto; margin-right:auto; max-width:300px;">
                        <span class="glyphicon glyphicon-cloud-download"></span>&nbsp;&nbsp;Download PDF
                    </a>
                    <br />
                    <label>Your browser does not support embedded PDFs. Please click the button above to download the PDF.</label>
                </div>
            </div>
        }
    </div>
   

    @if (Model.Attachments.Count > 0)
    {
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4>Attachments</h4>
                    <hr />
                    @foreach (var a in Model.Attachments.Where(a => a.File.FileFormat == "Image"))
                    {
                        <a class="popup-image" target="_blank" href="@a.File.FilePath" download="@a.Filename" title="@a.Filename" style="text-decoration: none; display:inline-block; margin:5px">
                            <img src="@a.File.FilePath" class="img-rounded" style="height: 100px; width: 100px;" />
                        </a>
                    }
                    @foreach (var a in Model.Attachments.Where(a => a.File.FileFormat != "Image"))
                    {
                        <br />
                        <a class="popup-image" target="_blank" href="@a.File.FilePath" download="@a.Filename" title="@a.Filename" style="text-decoration: none">
                            <span class="glyphicon glyphicon-paperclip" style="font-size: large; margin: 10px;"></span>@a.Filename
                        </a>
                    }
                </div>
            </div>
        </div>
    }
</div>


@if (!Model.HasAgreement)
{

    <a id="Button_Close_Content" class="btn btn-background" onclick="HideViews()" style="z-index:1105; display:none;"></a>

    <div id="Content_Agreement" class="panel panel-default" style="z-index: 2130; position: absolute; width: 96%; max-width:500px; display: none; top: 10px; right:0; left:0; margin:auto; margin-top:30px; margin-bottom:-30px;">
        <div class="panel-heading">
            <h4 style="display:inline-block">Accept Quotation</h4>
            <a class="btn btn-default" href="#" onclick="HideViews()" style="float:right"><span class="glyphicon glyphicon-remove"></span>Close</a>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12">
                    @Html.Action("_AcceptReject", "QuotationAgreements", new { ID = Model.ID, Jasq = Model.CheckSum })
                </div>
            </div>
        </div>
    </div>

    <script>
        function SubmitAgreement(){
            $("#Content_Agreement").fadeIn();
            $("#Button_Close_Content").fadeIn();
            $("#divPDFView").fadeOut();
        }

        function HideViews(){
            $("#Content_Agreement").fadeOut();
            $("#Button_Close_Content").fadeOut();
            $("#divPDFView").fadeIn();
        }
    </script>

}


@if (ViewBag.SavedDraftID != null && ViewBag.SavedDraftCheckSum != null && Model.StatusID < SnapSuite.Models.QuotationStatusValues.ACCEPTED)
{
    <div id="myCustomQuotationModel" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myCustomQuotationModel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content" style="padding:15px; text-align:center; align-items:center">
                <h4>Saved Custom Quotation</h4>
                <hr />
                <p>A saved custom version the quotation has been found. Please click here to continue editing.</p>
                <a id="Button_Customize" class="btn btn-info" style="margin: 4px; text-align:center" href="@Url.Action("Customize", new { ID = ViewBag.SavedDraftID, Jasq = ViewBag.SavedDraftCheckSum })"><span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Edit Customized Quotation</a>
            </div>
        </div>
    </div>

    <script>
        setTimeout(function(){
            $('#myCustomQuotationModel').modal('show');
        },1000);
    </script>
}

PutneyAndWood/Views/QuotationReview/SubmitComplete.cshtml
@{
    ViewBag.Title = "Custom Quotation Submitted for Review";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>@ViewBag.Title</h1>
            <hr />
            <p class="text-default">
                Thank you for submitting you custom quotation for review.
                <br />
                Someone will be in contact shortly.
            </p>
        </div>
    </div>
</div>
<div class="row">

</div>

PutneyAndWood/Views/QuotationReview/_Header.cshtml
@using SnapSuite.Models
@model QuotationClientViewModel

<div class="panel panel-primary">
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-4">
                <label>For the attention of:</label><br />
                @foreach(var i in Model.InvoiceAddress.Split(new string[] { ", " }, StringSplitOptions.RemoveEmptyEntries))
                {
                    <span>@i</span><br />
                }
            </div>
            <div class="col-sm-4">
                @if (!string.IsNullOrWhiteSpace(Model.DeliveryAddress))
                {
                    <label>Delivery Address:</label><br />
                    foreach (var i in Model.DeliveryAddress.Split(new string[] { ", " }, StringSplitOptions.RemoveEmptyEntries))
                    {
                        <span>@i</span><br />
                    }
                }
            </div>
            <div class="col-sm-4" style="text-align:right">
                <br />
                <br />
                <p style="font-size: small">
                    <strong>
                        @string.Format("Net: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalNet)
                    </strong>
                </p>
                <p style="font-size: small">
                    <strong>
                        @string.Format("Tax: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalVat)
                    </strong>
                </p>

                <h4 style="font-weight: normal">
                    <strong>
                        @string.Format("Total Price: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalPrice)
                    </strong>
                </h4>
            </div>
        </div>
        
    </div>
</div>

PutneyAndWood/Views/QuotationReview/_HeaderTotal.cshtml
@using SnapSuite.Models
@model QuotationClientViewModel

@if (!Model.UsePriceBreaks)
{
    <div class="col-xs-6" style="padding: 0; margin: 0; text-align:right">
        <hr />
        <p style="font-size: small">
            @string.Format("Products Margin: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalMargin)
            &nbsp;
            @string.Format("({0:N2}%)", Model.Margin)
        </p>
        <p style="font-size: small">
            @string.Format("Item Costs: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalCost)
        </p>
        <p style="font-size: small">
            @string.Format("Additional Costs: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalOtherCosts)
        </p>
        <p style="font-size: small">
            @string.Format("Labour: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalLabourCosts)
        </p>
    </div>
    <div class="col-xs-6" style="padding: 0; margin: 0; text-align:right">
        <hr />
        <p style="font-size: small">
            @string.Format("Discount: {0:N2}%", Model.Discount)
        </p>
        <p style="font-size: small">
            @string.Format("Net: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalNet)
        </p>
        <p style="font-size: small">
            @string.Format("Tax: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalVat)
        </p>

        <h4 style="font-weight: normal">
            <strong>
                @string.Format("Total Price: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalPrice)
            </strong>
        </h4>
        <p style="font-size: small; font-weight:bold; color: @((Model.TotalProfit < 0) ? "red" : "darkgreen")">
            @string.Format("Profit: {0:" + Model.CurrencySymbol + "#,##0.#0} ({1:#,##0.00}%)", Model.TotalProfit, Model.Profit)
        </p>
    </div>
}

PutneyAndWood/Views/QuotationReview/_ItemImage.cshtml
@using SnapSuite.Models; 

<script type="text/x-kendo-tmpl" id="Item-Image-Template">
    <div class="product-thumbnail-container">
        <div class="product-thumbnail">
            <a class='popup-image popup-image-max' target='_blank' href='#:File.FilePath#'>
                <img class="image-thumbnail" src="#:File.FilePath#" >
            </a>
        </div>
    </div>
</script>

<div class="panel panel-default">
    <div class="panel-body product-images">

        <div class="row">
            <div class="col-xs-7">
                <h3>Images</h3>
            </div>
            <div class="col-xs-5">
                <a class="btn btn-sm btn-default" onclick="HideViews(); return false;" style="float:right;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
            </div>
            <div class="col-xs-12"> 
                <br />
                @(Html.Kendo().ListView<ImageViewModel>()
                    .Name("ItemImageListView")
                    .TagName("div")
                    .ClientTemplateId("Item-Image-Template")
                    .DataSource(dataSource =>
                    {
                        dataSource.Read(read => read.Action("ReadImages", "ClientQuotationItems", new { ID = ViewBag.ID }));
                    })
                )
            </div>
        </div>
    </div>
</div>

PutneyAndWood/Views/QuotationReview/_SectionTotal.cshtml
@model SnapSuite.Models.QuotationSectionClientViewModel

@if (Model.IncludeInTotal)
{
    <div style="padding: 0; margin: 0; text-align:right">    
        <p style="font-size: small; ">
            <strong>
                @string.Format("Net: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalNet)
                &nbsp;&nbsp;
                @string.Format("Tax: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalVat)
            </strong>
        </p>
        <h5 style="font-weight: normal;">
            <strong>
                @string.Format("Total: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalPrice)
            </strong>
        </h5>       
    </div>
}
else
{
    <div style="padding: 0; margin: 0; text-align:right; color:grey;">
        <p style="font-size: small; color:grey;">
            <strong>
                @string.Format("Net: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalNet)
                &nbsp;&nbsp;
                @string.Format("Tax: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalVat)
            </strong>
        </p>
        <h5 style="font-weight: normal; color:grey;">
            <strong>
                @string.Format("Total: {0:" + Model.CurrencySymbol + "#,##0.#0}", Model.TotalPrice)
            </strong>
        </h5>
    </div>
}